import "@/styles/index.scss"

import { Montserrat } from "next/font/google"
import { Navbar } from "@/components/index"

// Font config
const montserrat = Montserrat({
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
